[AirIndex Issue 9] Add reload script and update main.cppAdd reload script and update main file
illinoisdata/RMI pull request #1
Opened 2022-03-13 20:22 UTC by pseudoinverse

This PR is related to [this issue](https://github.com/illinoisdata/airindex/issues/9) and mainly consists of three modifications:

1. Add a reload script `optimizer.sh`. It is used to run the auto-tuning optimizer on SOSD dataset.
2. Update `main.cpp` to check if the RMI index is equal to the expected answer.
3. Update `main.cpp` to print metrics at each milestone.

2022-03-14 23:20 UTC, mIXs222 requested changes
Looks good overall. One logic requested change + small tidying comments

Could you attach a screenshot/paste of benchmark runs (one for `whole`, one for `mmap` version) in this PR? Also, the output file as well?

2022-03-14 23:20 UTC, mIXs222 commented on tests/kv_test/main.cpp
>      if (((((t_idx + 1) & (t_idx)) == 0) && (t_idx < 999)) || ((t_idx >= 999) & (t_idx % 1000 == 999))) {
Can you update this milestone predicate too? This builds `timestamps`, to be saved to file later.

2022-03-14 23:20 UTC, mIXs222 commented on tests/kv_test/main.cpp
>      if (((((t_idx + 1) & (t_idx)) == 0) && (t_idx < 999)) || ((t_idx >= 999) & (t_idx % 1000 == 999))) {
Alternatively, move `timesstamps.push_back(...)` into `if` above.

2022-03-14 23:20 UTC, mIXs222 commented on tests/kv_test/main.cpp
> +		  << " RMI guess:" << true_index << std::endl;
nit: `RMI guess` --> `RMI answer`

2022-03-14 23:20 UTC, mIXs222 commented on tests/kv_test/main.cpp
> +	count_milestone = ceil(((double) count_milestone) * freq_mul);  // next milestone to print
Possibly merge this reporting with `report_t`? Feel free to extend its arguments.

2022-03-14 23:20 UTC, mIXs222 commented on tests/kv_test/main.cpp
>    // TODO: load keys
Could you remove `TODO`? This is my mistake leaving it behind 😅

2022-03-18 22:16 UTC, pseudoinverse commented
> Looks good overall. One logic requested change + small tidying comments
> 
> Could you attach a screenshot/paste of benchmark runs (one for `whole`, one for `mmap` version) in this PR? Also, the output file as well?
```
Testing mmap
>>> wiki_ts_200M_uint64 0
vm.drop_caches = 3
0.014
reload_nfs.sh completed
found flag data_path = index-nfs/data/wiki_ts_200M_uint64
found flag key_path = index-nfs/keyset/wiki_ts_200M_uint64_ks
found flag rmi_data_path = index-nfs/storage/wiki_ts_200M_uint64_rmi_mmap/rmi_data
found flag out_path = index-nfs/out/out_main_wiki_ts_200M_uint64_rmi_mmap.txt
RMI status: 1
<<< 190300301 ns  to finish 1 queries.
t = 190348701 ns: 1 counts, tot 190348701/op, seg 190348701/op
Search key: 1200309221 RMI guess: 162055137 +/- 6 Key at 162055136: 1200309221 diff: 1
<<< 231693688 ns  to finish 2 queries.
t = 231737589 ns: 2 counts, tot 115868794/op, seg 41388888/op
<<< 299604452 ns  to finish 3 queries.
t = 299646452 ns: 3 counts, tot 99882150/op, seg 67908863/op
<<< 334195943 ns  to finish 4 queries.
t = 334228243 ns: 4 counts, tot 83557060/op, seg 34581791/op
<<< 391849361 ns  to finish 5 queries.
t = 391871761 ns: 5 counts, tot 78374352/op, seg 57643518/op
<<< 419714156 ns  to finish 6 queries.
t = 419736456 ns: 6 counts, tot 69956076/op, seg 27864695/op
<<< 464547392 ns  to finish 7 queries.
t = 464571993 ns: 7 counts, tot 66367427/op, seg 44835537/op
<<< 500796407 ns  to finish 8 queries.
t = 500814507 ns: 8 counts, tot 62601813/op, seg 36242514/op
<<< 549782202 ns  to finish 9 queries.
t = 549802602 ns: 9 counts, tot 61089178/op, seg 48988095/op
<<< 586758127 ns  to finish 10 queries.
t = 586784127 ns: 10 counts, tot 58678412/op, seg 36981525/op
<<< 621498420 ns  to finish 11 queries.
t = 621525720 ns: 11 counts, tot 56502338/op, seg 34741593/op
<<< 699942633 ns  to finish 13 queries.
t = 699982533 ns: 13 counts, tot 53844810/op, seg 39228406/op
<<< 781040184 ns  to finish 15 queries.
t = 781077984 ns: 15 counts, tot 52071865/op, seg 40547725/op
<<< 854666528 ns  to finish 17 queries.
t = 854699829 ns: 17 counts, tot 50276460/op, seg 36810922/op
<<< 932111127 ns  to finish 19 queries.
t = 932145228 ns: 19 counts, tot 49060275/op, seg 38722699/op
<<< 1031348236 ns  to finish 21 queries.
t = 1031382636 ns: 21 counts, tot 49113458/op, seg 49618704/op
<<< 1179033031 ns  to finish 24 queries.
t = 1179058232 ns: 24 counts, tot 49127426/op, seg 49225198/op
<<< 1339028902 ns  to finish 27 queries.
t = 1339063502 ns: 27 counts, tot 49594944/op, seg 53335090/op
<<< 1456608470 ns  to finish 30 queries.
t = 1456641471 ns: 30 counts, tot 48554715/op, seg 39192656/op
<<< 1603242651 ns  to finish 33 queries.
t = 1603275952 ns: 33 counts, tot 48584119/op, seg 48878160/op
<<< 1718198383 ns  to finish 37 queries.
t = 1718227583 ns: 37 counts, tot 46438583/op, seg 28737907/op
<<< 1885120851 ns  to finish 41 queries.
t = 1885155852 ns: 41 counts, tot 45979411/op, seg 41732067/op
<<< 2043061293 ns  to finish 46 queries.
t = 2043092093 ns: 46 counts, tot 44415045/op, seg 31587248/op
<<< 2208503340 ns  to finish 51 queries.
t = 2208534141 ns: 51 counts, tot 43304591/op, seg 33088409/op
<<< 2386805971 ns  to finish 57 queries.
t = 2386850071 ns: 57 counts, tot 41874562/op, seg 29719321/op
<<< 2582996255 ns  to finish 63 queries.
t = 2583037655 ns: 63 counts, tot 41000597/op, seg 32697930/op
<<< 2791734817 ns  to finish 70 queries.
t = 2791762617 ns: 70 counts, tot 39882323/op, seg 29817851/op
<<< 3001743597 ns  to finish 77 queries.
t = 3001787198 ns: 77 counts, tot 38984249/op, seg 30003511/op
<<< 3306728525 ns  to finish 85 queries.
t = 3306763626 ns: 85 counts, tot 38903101/op, seg 38122053/op
<<< 3636133600 ns  to finish 94 queries.
t = 3636164200 ns: 94 counts, tot 38682597/op, seg 36600063/op
<<< 3975854020 ns  to finish 104 queries.
t = 3975896321 ns: 104 counts, tot 38229772/op, seg 33973212/op
<<< 4306819617 ns  to finish 115 queries.
t = 4306846918 ns: 115 counts, tot 37450842/op, seg 30086417/op
<<< 4710120458 ns  to finish 127 queries.
t = 4710154559 ns: 127 counts, tot 37087831/op, seg 33608970/op
<<< 5118716178 ns  to finish 140 queries.
t = 5118743378 ns: 140 counts, tot 36562452/op, seg 31429909/op
<<< 5461268656 ns  to finish 154 queries.
t = 5461302157 ns: 154 counts, tot 35463001/op, seg 24468484/op
<<< 5886531513 ns  to finish 170 queries.
t = 5886563914 ns: 170 counts, tot 34626846/op, seg 26578859/op
<<< 6364126715 ns  to finish 188 queries.
t = 6364168916 ns: 188 counts, tot 33851962/op, seg 26533611/op
<<< 6826960207 ns  to finish 207 queries.
t = 6826991007 ns: 207 counts, tot 32980632/op, seg 24359057/op
<<< 7387117885 ns  to finish 228 queries.
```

```
Testing whole
>>> wiki_ts_200M_uint64 0
vm.drop_caches = 3
0.016
reload_nfs.sh completed
found flag data_path = index-nfs/data/wiki_ts_200M_uint64
found flag key_path = index-nfs/keyset/wiki_ts_200M_uint64_ks
found flag rmi_data_path = index-nfs/storage/wiki_ts_200M_uint64_rmi_whole/rmi_data
found flag out_path = index-nfs/out/out_main_wiki_ts_200M_uint64_rmi_whole.txt
RMI status: 1
<<< 6103681210 ns  to finish 1 queries.
t = 6103709110 ns: 1 counts, tot 6103709110/op, seg 6103709110/op
Search key: 1200309221 RMI guess: 162055137 +/- 6 Key at 162055136: 1200309221 diff: 1
<<< 6113047060 ns  to finish 2 queries.
t = 6113069160 ns: 2 counts, tot 3056534580/op, seg 9360050/op
<<< 6122325209 ns  to finish 3 queries.
t = 6122341609 ns: 3 counts, tot 2040780536/op, seg 9272449/op
<<< 6131593058 ns  to finish 4 queries.
t = 6131614558 ns: 4 counts, tot 1532903639/op, seg 9272949/op
<<< 6140500900 ns  to finish 5 queries.
t = 6140526601 ns: 5 counts, tot 1228105320/op, seg 8912043/op
<<< 6148753633 ns  to finish 6 queries.
t = 6148767533 ns: 6 counts, tot 1024794588/op, seg 8240932/op
<<< 6157457672 ns  to finish 7 queries.
t = 6157471872 ns: 7 counts, tot 879638838/op, seg 8704339/op
<<< 6165967509 ns  to finish 8 queries.
t = 6165991509 ns: 8 counts, tot 770748938/op, seg 8519637/op
<<< 6174913252 ns  to finish 9 queries.
t = 6174931352 ns: 9 counts, tot 686103483/op, seg 8939843/op
<<< 6183197085 ns  to finish 10 queries.
t = 6183223185 ns: 10 counts, tot 618322318/op, seg 8291833/op
<<< 6192020426 ns  to finish 11 queries.
t = 6192041727 ns: 11 counts, tot 562912884/op, seg 8818542/op
<<< 6211171134 ns  to finish 13 queries.
t = 6211194634 ns: 13 counts, tot 477784202/op, seg 9576453/op
<<< 6228921118 ns  to finish 15 queries.
t = 6228952119 ns: 15 counts, tot 415263474/op, seg 8878742/op
<<< 6246363498 ns  to finish 17 queries.
t = 6246379798 ns: 17 counts, tot 367434105/op, seg 8713839/op
<<< 6263061466 ns  to finish 19 queries.
t = 6263089566 ns: 19 counts, tot 329636292/op, seg 8354884/op
<<< 6281209357 ns  to finish 21 queries.
t = 6281222957 ns: 21 counts, tot 299105855/op, seg 9066695/op
<<< 6308857300 ns  to finish 24 queries.
t = 6308879300 ns: 24 counts, tot 262869970/op, seg 9218781/op
<<< 6334366409 ns  to finish 27 queries.
t = 6334391509 ns: 27 counts, tot 234607092/op, seg 8504069/op
<<< 6363274173 ns  to finish 30 queries.
t = 6363304973 ns: 30 counts, tot 212110165/op, seg 9637821/op
<<< 6391914032 ns  to finish 33 queries.
t = 6391939432 ns: 33 counts, tot 193695134/op, seg 9544819/op
<<< 6428062111 ns  to finish 37 queries.
t = 6428093912 ns: 37 counts, tot 173732267/op, seg 9038620/op
<<< 6465483111 ns  to finish 41 queries.
t = 6465511212 ns: 41 counts, tot 157695395/op, seg 9354325/op
<<< 6515463913 ns  to finish 46 queries.
t = 6515496813 ns: 46 counts, tot 141641235/op, seg 9997120/op
<<< 6565343813 ns  to finish 51 queries.
t = 6565372813 ns: 51 counts, tot 128732800/op, seg 9975200/op
<<< 6610801042 ns  to finish 57 queries.
t = 6610837842 ns: 57 counts, tot 115979611/op, seg 7577504/op
<<< 6666115529 ns  to finish 63 queries.
t = 6666142029 ns: 63 counts, tot 105811778/op, seg 9217364/op
<<< 6729214440 ns  to finish 70 queries.
t = 6729242841 ns: 70 counts, tot 96132040/op, seg 9014401/op
<<< 6792247851 ns  to finish 77 queries.
t = 6792274252 ns: 77  [...]

2022-03-21 04:03 UTC, mIXs222 approved these changes
A few corrections left. Could you attach the full stdout logs as before, after fixing these?

Feel free to merge when you're ready. The code should be good to run the full RMI benchmark afterward.

2022-03-21 04:03 UTC, mIXs222 commented on tests/kv_test/main.cpp
> +    if (t_idx + 1 == count_milestone) {
missing last milestone when at `queries.size()`

2022-03-21 04:03 UTC, mIXs222 commented on tests/kv_test/main.cpp
> +  long long time_elapsed = std::chrono::duration_cast<std::chrono::nanoseconds>(curr_time - start_t).count();
`(lookups_end_time, lookup_time)` is redundant to `(curr_time, time_elapsed)`. Could you pick one and remove another?

Also, remove the print on line 24 as well since we have a better print on 27-29.

2022-03-21 04:03 UTC, mIXs222 commented on tests/kv_test/main.cpp
>    auto timestamps = std::vector<double>();
This is minor, but could you move this up before starting the clock? Ideally, we should try to control variables as much as possible.

2022-03-22 14:58 UTC, pseudoinverse commented
> A few corrections left. Could you attach the full stdout logs as before, after fixing these?
> 
> Feel free to merge when you're ready. The code should be good to run the full RMI benchmark afterward.

mmap:
```
Testing mmap
>>> wiki_ts_200M_uint64 0
vm.drop_caches = 3
0.013
reload_nfs.sh completed
found flag data_path = index-nfs/data/wiki_ts_200M_uint64
found flag key_path = index-nfs/keyset/wiki_ts_200M_uint64_ks
found flag rmi_data_path = index-nfs/storage/wiki_ts_200M_uint64_rmi_mmap/rmi_data
found flag out_path = index-nfs/out/out_main_wiki_ts_200M_uint64_rmi_mmap.txt
RMI status: 1
t = 127383605 ns: 1 counts, tot 127383605/op, seg 127383605/op
Search key: 1200309221 RMI guess: 162055137 +/- 6 Key at 162055136: 1200309221 diff: 1
t = 181053636 ns: 2 counts, tot 90526818/op, seg 53670031/op
t = 221960417 ns: 3 counts, tot 73986805/op, seg 40906781/op
t = 249325639 ns: 4 counts, tot 62331409/op, seg 27365222/op
t = 270111383 ns: 5 counts, tot 54022276/op, seg 20785744/op
t = 314261802 ns: 6 counts, tot 52376967/op, seg 44150419/op
t = 354564777 ns: 7 counts, tot 50652111/op, seg 40302975/op
t = 422468975 ns: 8 counts, tot 52808621/op, seg 67904198/op
t = 452068423 ns: 9 counts, tot 50229824/op, seg 29599448/op
t = 488587753 ns: 10 counts, tot 48858775/op, seg 36519330/op
t = 522445151 ns: 11 counts, tot 47495013/op, seg 33857398/op
t = 585143088 ns: 13 counts, tot 45011006/op, seg 31348968/op
t = 647415621 ns: 15 counts, tot 43161041/op, seg 31136266/op
t = 729250283 ns: 17 counts, tot 42897075/op, seg 40917331/op
t = 822055375 ns: 19 counts, tot 43266072/op, seg 46402546/op
t = 879109846 ns: 21 counts, tot 41862373/op, seg 28527235/op
t = 952802513 ns: 24 counts, tot 39700104/op, seg 24564222/op
t = 1040928549 ns: 27 counts, tot 38552909/op, seg 29375345/op
t = 1127274265 ns: 30 counts, tot 37575808/op, seg 28781905/op
t = 1219942155 ns: 33 counts, tot 36967944/op, seg 30889296/op
t = 1327390318 ns: 37 counts, tot 35875414/op, seg 26862040/op
t = 1439685039 ns: 41 counts, tot 35114269/op, seg 28073680/op
t = 1581136103 ns: 46 counts, tot 34372523/op, seg 28290212/op
t = 1726960318 ns: 51 counts, tot 33861967/op, seg 29164843/op
t = 1874348151 ns: 57 counts, tot 32883300/op, seg 24564638/op
t = 1994628266 ns: 63 counts, tot 31660766/op, seg 20046685/op
t = 2163044747 ns: 70 counts, tot 30900639/op, seg 24059497/op
t = 2319325285 ns: 77 counts, tot 30121107/op, seg 22325791/op
t = 2557734089 ns: 85 counts, tot 30090989/op, seg 29801100/op
t = 2767799860 ns: 94 counts, tot 29444679/op, seg 23340641/op
t = 3017722099 ns: 104 counts, tot 29016558/op, seg 24992223/op
t = 3274390018 ns: 115 counts, tot 28472956/op, seg 23333447/op
t = 3548174038 ns: 127 counts, tot 27938378/op, seg 22815335/op
t = 3790932093 ns: 140 counts, tot 27078086/op, seg 18673696/op
t = 4071406992 ns: 154 counts, tot 26437707/op, seg 20033921/op
t = 4420367696 ns: 170 counts, tot 26002162/op, seg 21810044/op
t = 4807657251 ns: 188 counts, tot 25572644/op, seg 21516086/op
```

whole:
```
>>> books_800M_uint64 0                                                                                                                
vm.drop_caches = 3                                                                                                                     
0.016                                                                                                                                  
reload_nfs.sh completed                                                                                                                
found flag data_path = index-nfs/data/books_800M_uint64                                                                                
found flag key_path = index-nfs/keyset/books_800M_uint64_ks                                                                            
found flag rmi_data_path = index-nfs/storage/books_800M_uint64_rmi_whole/rmi_data                                                      
found flag out_path = index-nfs/out/out_main_books_800M_uint64_rmi_whole.txt                                                           
RMI status: 1                                                                                                                          
t = 6306502359 ns: 1 counts, tot 6306502359/op, seg 6306502359/op                                                                      
Search key: 4543777083538785024 RMI guess: 675333712 +/- 11 Key at 675333716: 4543777083538785024 diff: 4                              
t = 6317377404 ns: 2 counts, tot 3158688702/op, seg 10875045/op                                                                        
t = 6328499852 ns: 3 counts, tot 2109499950/op, seg 11122448/op                                                                        
t = 6338034879 ns: 4 counts, tot 1584508719/op, seg 9535027/op                                                                         
t = 6349788835 ns: 5 counts, tot 1269957767/op, seg 11753956/op                                                                        
t = 6362396103 ns: 6 counts, tot 1060399350/op, seg 12607268/op                                                                        
t = 6373562252 ns: 7 counts, tot 910508893/op, seg 11166149/op                                                                         
t = 6383407483 ns: 8 counts, tot 797925935/op, seg 9845231/op                                                                                                                                                                                                                 
t = 6394159126 ns: 9 counts, tot 710462125/op, seg 10751643/op                                                                         
t = 6403812154 ns: 10 counts, tot 640381215/op, seg 9653028/op                                                                         
t = 6414616898 ns: 11 counts, tot 583146990/op, seg 10804744/op                                                                                                                                                                                                               
t = 6437403101 ns: 13 counts, tot 495184853/op, seg 11393101/op                                                                        
t = 6458653684 ns: 15 counts, tot 430576912/op, seg 10625291/op                                                                        
t = 6481565288 ns: 17 counts, tot 381268546/op, seg 11455802/op                                                                        
t = 6504717996 ns: 19 counts, tot 342353578/op, seg 11576354/op                                                                        
t = 6526972892 ns: 21 counts, tot 310808232/op, seg 11127448/op                                                                        
t = 6561360650 ns: 24 counts, tot 273390027/op, seg 11462586/op                                                                        
t = 6592285461 ns: 27 counts, tot 244158720/op, seg 10308270/op                                                                        
t = 6623517877 ns: 30 counts, tot 220783929/op, seg 10410805/op                                                                        
t = 6655445701 ns: 33 counts, tot 201680172/op, seg 10642608/op                                                                        
t = 6701268511 ns: 37 counts, tot 181115365/op, seg 11455702/op                                                                        
t = 6744418185 ns: 41 counts, tot 164498004/op, seg 10787418/op                                                                        
t = 6795408163 ns: 46 counts, tot 147726264/op, seg 10197995/op                                                                        
t = 6845717533 ns: 51 counts, tot 134229755/op, seg 10061874/op                                                                        
t = 6909649283 ns: 57 counts, tot 121221917/op, seg 10655291/op                              [...]

2022-03-26 22:50 UTC, merged